### ISSUE TITLE
USER STORY: Create Login/Logout function

### ISSUE THREAD

**Issue by TomaszWoloszyn983** [TomaszWoloszyn983/shopping-list-application#6]
As a **user** I can **register and login** so that **I can receive access to additional functions.**

### Tasks:
- [x] Create register function
- [x] Create login function
- [x] Create logout function
